# Generated by Django 5.2.17 on 2026-08-20

from django.db import migrations, models


def populate_homebytes_email(apps, schema_editor):
    Vendor = apps.get_model("Orders", "Vendor")
    Vendor.objects.filter(name="HomeBytes").update(
        email_address="info@homebytes.co.in"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("Orders", "0002_incomingemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="email_address",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.RunPython(populate_homebytes_email, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="vendor",
            name="email_address",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
