# Generated by Django 5.2.17 on 2026-08-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_vendor_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill_printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='bill_printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
