# Generated by Django 5.2.17 on 2026-08-20 13:52

from django.db import migrations, models


def copy_operational_order_dates(apps, schema_editor):
    Order = apps.get_model("Orders", "Order")
    for order in Order.objects.all().iterator():
        order.order_date = order.delivery_date or order.booking_date
        order.save(update_fields=["order_date"])


def restore_delivery_dates(apps, schema_editor):
    Order = apps.get_model("Orders", "Order")
    for order in Order.objects.exclude(order_date__isnull=True).iterator():
        order.delivery_date = order.order_date
        order.save(update_fields=["delivery_date"])


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_order_bill_printed_order_bill_printed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(copy_operational_order_dates, restore_delivery_dates),
        migrations.RemoveField(
            model_name='order',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
    ]
