# Generated by Django 5.2.17 on 2026-08-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_remove_order_booking_date_remove_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingemail',
            name='processing_status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped (non-order email)')], default='RECEIVED', max_length=10),
        ),
    ]
