# Generated by Django 5.2.17 on 2026-08-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_alter_incomingemail_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='train_journey_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
