# Generated by Django 5.2.17 on 2026-08-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_order_train_journey_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('vendor', 'order_number'), name='unique_order_per_vendor_order_number'),
        ),
    ]
