# Generated by Django 5.2.17 on 2026-08-29 21:21

from django.db import migrations, models


def migrate_existing_demo_vendors(apps, schema_editor):
    Vendor = apps.get_model("Orders", "Vendor")
    Vendor.objects.filter(is_demo=True, parser_type="RAILRESTRO").update(parser_type="DEMO")


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0014_restaurant_paid_subscription_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='parser_type',
            field=models.CharField(choices=[('DEMO', 'TrainPOS Demo'), ('RAILRESTRO', 'RailRestro'), ('HOMEBYTES', 'HomeBytes'), ('RAJBHOG', 'Rajbhog Khana'), ('RAILRECIPE', 'RailRecipe')], default='RAILRESTRO', max_length=20),
        ),
        migrations.RunPython(migrate_existing_demo_vendors, migrations.RunPython.noop),
    ]
