# Generated by Django 5.2.17 on 2026-08-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0015_alter_vendor_parser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingemail',
            name='processing_status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('INVALID', 'Invalid (terminal parser/validation failure)'), ('SKIPPED', 'Skipped (non-order email)')], default='RECEIVED', max_length=10),
        ),
    ]
